#!/bin/sh

# Redirect output to stderr.
exec 1>&2

ROOT="$PWD"
PHP_CS_FIXER="${ROOT}/bin/php vendor/bin/php-cs-fixer"

git status --porcelain | grep -e '^[AM]\(.*\).php$' | cut -c 3- | while read line; do
    $PHP_CS_FIXER fix --verbose "$line";
    git add "$line";
done
